### ISSUE TITLE
data.csv 的 description 为空

### ISSUE THREAD

**Issue by PatZhuang** [abc1763613206/myiptv#3]
脚本里会读 csv 的第4栏，也就是 description，但是我看 csv 文件里这一栏都是空的，请问这个值是从什么地方获取到的？

**Comment by abc1763613206** [comment]
这个项目基本上是自己日用，做完我就搁置了，还请谅解（      
是这样，目前节目源都是人工维护，计划在这里塞点码率和HDR相关的内容，注释里有说： https://github.com/abc1763613206/myiptv/blob/main/main.py#L20

这个主要也是为了自己维护着方便，毕竟这个 csv 我也是拿 Excel 这一类维护，真要有描述的话拉一行也好加。但如果没有的话，您就当这一项不存在好了。

毕竟没有描述的情况我也已经做了 fallback ，见：https://github.com/abc1763613206/myiptv/blob/main/main.py#L110-L114

**Comment by abc1763613206** [comment]
@PatZhuang 关于 Description 的问题在 https://github.com/abc1763613206/myiptv/commit/6ed661de63dfbf6a974d0f5f128300e9d0fd30d3 修了
